# Generated by Django 5.1 on 2024-09-02 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_direc', models.CharField(max_length=50)),
                ('e_mail_secre_direc', models.EmailField(max_length=50)),
                ('secre_direc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_pole', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_site', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ListeDePersonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Liste_Pers', models.CharField(max_length=50)),
                ('date_recep', models.DateField(max_length=50)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listes', to='App_astreinte.direction')),
            ],
        ),
        migrations.AddField(
            model_name='direction',
            name='pole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='App_astreinte.pole'),
        ),
        migrations.CreateModel(
            name='FaireLAstreinte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deb', models.DateField()),
                ('date_fin', models.DateField()),
                ('num_sem', models.CharField(max_length=50)),
                ('ListeDePersonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_astreinte.listedepersonne')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_astreinte.site')),
            ],
        ),
        migrations.CreateModel(
            name='SousDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_sous_direc', models.CharField(max_length=50)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_directions', to='App_astreinte.direction')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_ag', models.CharField(max_length=50)),
                ('nom_ag', models.CharField(max_length=50)),
                ('tel_ag', models.CharField(max_length=50)),
                ('cell_ag', models.CharField(max_length=50)),
                ('sous_direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='App_astreinte.sousdirection')),
            ],
        ),
    ]
