# Generated by Django 5.1 on 2024-09-18 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_astreinte', '0002_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='mat_ag',
        ),
        migrations.AddField(
            model_name='agent',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='App_astreinte.direction'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='sous_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='App_astreinte.sousdirection'),
        ),
    ]
