# Generated by Django 5.1 on 2024-09-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_astreinte', '0003_remove_agent_mat_ag_agent_direction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='pole',
        ),
    ]
