# Generated by Django 5.1 on 2024-09-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_astreinte', '0004_remove_direction_pole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='tel_ag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
