# Generated by Django 5.1 on 2024-09-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_astreinte', '0005_alter_agent_tel_ag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='cell_ag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='nom_ag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
