# Generated by Django 5.1 on 2024-09-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_astreinte', '0006_alter_agent_cell_ag_alter_agent_nom_ag'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='prenom_ag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
