# Generated by Django 5.1 on 2024-09-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_astreinte', '0007_agent_prenom_ag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fairelastreinte',
            name='site',
        ),
        migrations.AddField(
            model_name='fairelastreinte',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='astreintes/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='cell_ag',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='tel_ag',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
